name: Windows C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20

    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      
    # Install ISPC (Intel Implicit SPMD Program Compiler)
    - name: Install ISPC
      run: |
        powershell Invoke-WebRequest -Uri https://github.com/ispc/ispc/releases/download/v1.13.0/ispc-v1.13.0-windows.zip -OutFile ispc-v1.13.0-windows.zip
        powershell Expand-Archive -LiteralPath ispc-v1.13.0-windows.zip -DestinationPath C:\ispc
        
    # Install YASM
    - name: Install YASM
      run: |
        mkdir C:\yasm\bin
        powershell Invoke-WebRequest -Uri https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0-win64.exe -OutFile C:\yasm\bin\yasm.exe

    # Install NASM
    - name: Install NASM
      run: |
        powershell Invoke-WebRequest -Uri https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/win64/nasm-2.15.03-win64.zip -OutFile nasm-2.15.03-win64.zip
        powershell Expand-Archive -LiteralPath nasm-2.15.03-win64.zip -DestinationPath C:\nasm
        move C:\nasm\nasm-2.15.03 C:\nasm\bin
        
    # Install Infozip
    - name: Install Infozip
      run: |
        powershell Invoke-WebRequest -Uri https://github.com/LuaDist/zip/archive/3.0-Windows-x86.zip -OutFile zip-3.0-Windows-x86.zip
        powershell Expand-Archive -LiteralPath zip-3.0-Windows-x86.zip -DestinationPath C:\zip
        move c:\zip\zip-3.0-Windows-x86\* c:\zip

    # TODO: need to install opencl, cuda

    - name: Build dnetc (32-bit)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        set PATH=%PATH%;C:\ispc\bin;C:\nasm\bin;C:\yasm\bin;C:\zip\bin
        echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
        echo PATH=%PATH%
        cd %GITHUB_WORKSPACE%\public
        nmake -f makefile.vc makezip

    - name: Test dnetc (32-bit)
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%\public
        dnetc.com -test

    - uses: actions/upload-artifact@v4
      with:
        name: dnetc-artifact-win32
        path: public/dnetc*-win32-x86.zip

    - name: Build dnetc (64-bit)
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=%PATH%;C:\ispc\bin;C:\nasm\bin;C:\yasm\bin;C:\zip\bin
        echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
        echo PATH=%PATH%
        cd %GITHUB_WORKSPACE%\public
        nmake -f makefile.vc superclean
        del dnetc*.zip
        C:\yasm\bin\yasm.exe -a x86 -m amd64 -o output\x86cpuid.obj -f win32 -D _WINDOWS plat\AMD64\x86cpuid.asm
        nmake -f makefile.vc makezip

    - name: Test dnetc (64-bit)
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%\public
        dnetc.com -test

    - uses: actions/upload-artifact@v4
      with:
        name: dnetc-artifact-win64
        path: public/dnetc*-win*.zip
